# Generated by Django 4.2.1 on 2023-06-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
