# Generated by Django 4.2.1 on 2023-06-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2023-06-26T00:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
