# Generated by Django 4.2.1 on 2023-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online Payment'), ('delivery', 'Pay on Delivery')], default='online', max_length=20),
        ),
    ]
