# Generated by Django 4.2.1 on 2023-07-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_order_stripe_charge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_charge_id',
        ),
    ]
