# Generated by Django 4.2.1 on 2023-07-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_order_delivery_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(default='Nairobi', max_length=50),
        ),
    ]
