# Generated by Django 4.2.1 on 2023-07-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
